### ISSUE TITLE
Feature Request: implement file upload / download when browsing a drive

### ISSUE THREAD

**Issue by blikblum** [yuudi/rclone-webui-angular#14]
Implement file upload / download when browsing a drive

**Comment by yuudi** [comment]
For now, file download is available on local instance. Download from remote instances need some workaround and I am going to figure it out later.

Uploading small file is not a problem but upload large file or upload directory might be challenging because of the limitation of rclone remote control.

I plan to implement upload small file before end of this month, but large file uploading depends on if I have time to make some modify on rclone backend.
